_attn_implementation_internal:
    value: null
_commit_hash:
    value: null
_name_or_path:
    value: runs/2r_w_beta_freq_Bfreeze_path_attn_from_s/checkpoint-80000
_output_attentions:
    value: false
_wandb:
    value:
        cli_version: 0.22.0
        e:
            1035wvchea3g5wq8q94s2o6vvpdcwscs:
                args:
                    - --model_type
                    - gpt2
                    - --tokenizer_name
                    - gpt2
                    - --share_freq_across_heads
                    - "True"
                    - --learning_rate
                    - "1e-4"
                    - --per_device_train_batch_size
                    - "16"
                    - --per_device_eval_batch_size
                    - "16"
                    - --block_size
                    - "512"
                    - --dataset_name
                    - xsum
                    - --dataset_config_name
                    - wikitext-103-raw-v1
                    - --do_train
                    - --do_eval
                    - --num_train_epochs
                    - "30"
                    - --num_harmonics
                    - "2"
                    - --eval_strategy
                    - steps
                    - --eval_steps
                    - "250"
                    - --logging_dir
                    - ./2r_w_beta_freq_Bfreeze_path_attn_from_s_xsum_log
                    - --logging_steps
                    - "250"
                    - --save_steps
                    - "250"
                    - --attn_implementation
                    - path_attn_wfreq
                    - --path_use_qk_norm
                    - "false"
                    - --path_use_low_rank_w
                    - "true"
                    - --path_use_w_shortconv
                    - "false"
                    - --path_conv_size
                    - "3"
                    - --warmup_steps
                    - "5000"
                    - --path_conv_bias
                    - "false"
                    - --output_dir
                    - runs/2r_w_beta_freq_Bfreeze_path_attn_from_s_xsum
                    - --gradient_accumulation_steps
                    - "2"
                    - --b_unfreeze_step
                    - "5000"
                    - --pe_method
                    - vanilla
                    - --single_A_B
                    - "False"
                    - --use_beta_modulation
                    - "True"
                    - --model_name_or_path
                    - runs/2r_w_beta_freq_Bfreeze_path_attn_from_s/checkpoint-80000
                codePath: examples/pytorch/language-modeling/run_clm.py
                codePathLocal: run_clm.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "957091000320"
                        used: "75025248256"
                email: hongyu.s.aa.titech@gmail.com
                executable: /cl/work5/hongyu-s/conda/envs/latest_transformers/bin/python3.12
                git:
                    commit: 2dfdced37b3f98bdeff9841d52407396f0fbd5f3
                    remote: git@github.com:Dearmer656/wavelet-path-attn.git
                gpu: NVIDIA RTX A6000
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-67507081-2329-2a07-3bdb-fca7dfa9e407
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-a2d6c189-dfdf-2e36-df98-1be337738648
                host: elm63
                memory:
                    total: "270092701696"
                os: Linux-5.15.0-131-generic-x86_64-with-glibc2.35
                program: /project/nlp-work5/hongyu-s/transformers/examples/pytorch/language-modeling/./run_clm.py
                python: CPython 3.12.11
                root: /project/nlp-work5/hongyu-s/transformers/examples/pytorch/language-modeling
                slurm:
                    cluster_name: naist-nlp
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    gpus_on_node: "2"
                    gtids: "0"
                    job_account: is-nlp
                    job_cpus_per_node: "4"
                    job_gid: "1000"
                    job_gpus: 0,1
                    job_id: "324063"
                    job_name: ""
                    job_nodelist: elm63
                    job_num_nodes: "1"
                    job_partition: gpu_long
                    job_qos: qos_is_nlp
                    job_uid: "40779"
                    job_user: hongyu-s
                    jobid: "324063"
                    localid: "0"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: elm63
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /project/nlp-work5/hongyu-s/transformers/examples/pytorch/language-modeling
                    submit_host: pine13
                    task_pid: "2838919"
                    tasks_per_node: "1"
                    topology_addr: naist.y2-118.elm63
                    topology_addr_pattern: switch.switch.node
                    working_cluster: naist-nlp:pine10:6817:9472:109
                startedAt: "2025-10-09T23:17:36.787205Z"
                writerId: 1035wvchea3g5wq8q94s2o6vvpdcwscs
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 100
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 100
            "3":
                - 16
            "4": 3.12.11
            "5": 0.22.0
            "6": 4.57.0.dev0
            "12": 0.22.0
            "13": linux-x86_64
activation_function:
    value: gelu_new
add_cross_attention:
    value: false
architectures:
    value:
        - GPT2LMHeadModel
attn_implementation:
    value: path_attn_wfreq
attn_pdrop:
    value: 0.1
bad_words_ids:
    value: null
begin_suppress_tokens:
    value: null
block_size:
    value: 512
bos_token_id:
    value: 50256
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
decoder_start_token_id:
    value: null
diversity_penalty:
    value: 0
do_sample:
    value: false
dtype:
    value: torch.float32
early_stopping:
    value: false
embd_pdrop:
    value: 0.1
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 50256
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
initializer_range:
    value: 0.02
is_decoder:
    value: false
is_encoder_decoder:
    value: false
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_norm_epsilon:
    value: 1e-05
length_penalty:
    value: 1
max_length:
    value: 20
min_length:
    value: 0
model_type:
    value: gpt2
n_embd:
    value: 768
n_head:
    value: 12
n_inner:
    value: null
n_layer:
    value: 12
n_positions:
    value: 1024
no_repeat_ngram_size:
    value: 0
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_harmonics:
    value: 2
num_return_sequences:
    value: 1
output_hidden_states:
    value: false
output_scores:
    value: false
pad_token_id:
    value: null
path_conv_bias:
    value: false
path_conv_size:
    value: 3
path_use_forget_gate:
    value: false
path_use_low_rank_w:
    value: true
path_use_qk_norm:
    value: false
path_use_w_shortconv:
    value: false
pe_method:
    value: vanilla
prefix:
    value: null
problem_type:
    value: null
remove_invalid_values:
    value: false
reorder_and_upcast_attn:
    value: false
repetition_penalty:
    value: 1
resid_pdrop:
    value: 0.1
return_dict:
    value: true
return_dict_in_generate:
    value: false
rope_theta:
    value: 10000
scale_attn_by_inverse_layer_idx:
    value: false
scale_attn_weights:
    value: true
sep_token_id:
    value: null
share_freq_across_heads:
    value: true
summary_activation:
    value: null
summary_first_dropout:
    value: 0.1
summary_proj_to_labels:
    value: true
summary_type:
    value: cls_index
summary_use_proj:
    value: true
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torchscript:
    value: false
transformers_version:
    value: 4.57.0.dev0
typical_p:
    value: 1
use_beta_modulation:
    value: true
use_cache:
    value: true
vocab_size:
    value: 50257
